packages:
  - apps/*
  - packages/*
catalog:
    turbo: ^2.2.3
    "@turbo/gen": ^2.2.3
    "@turbo/workspaces": ^2.2.3

    "@biomejs/biome": ^1.9.4

    husky: ^9.1.6

    "@commitlint/cli": ^19.5.0
    "@commitlint/config-conventional": ^19.5.0
    "@commitlint/config-pnpm-scopes": ^19.5.0
    "@commitlint/prompt-cli": ^19.5.0
    "@commitlint/types": ^19.5.0

    node: ^23.1.0
    "@types/node": ^22.9.0

    typescript: ^5.6.3
    ts-arithmetic: ^0.1.1
    ts-loader: ^9.5.1
    ts-node: ^10.9.2
    tsconfig-paths: ^4.2.0
    tsup: ^8.3.5
    source-map-support: ^0.5.21

    webpack: ^5.96.1
    webpack-node-externals: ^3.0.0
    "@types/webpack-node-externals": ^3.0.4
    run-script-webpack-plugin: ^0.2.0
    fork-ts-checker-webpack-plugin: ^9.0.2

    swc-loader: ^0.2.6
    "@swc/core": ^1.9.1
    "@swc/jest": ^0.2.37
    "@swc/cli": ^0.5.0

    "jest": ^29.7.0
    jest-extended: ^4.0.2
    ts-jest: ^29.2.5
    "@types/jest": ^29.5.14

    ajv: ^8.17.1
    ajv-formats: ^3.0.1
    ajv-errors: ^3.0.0

    reflect-metadata: ^0.2.2
    rxjs: ^7.8.1
    "@nestjs/common": ^10.4.7
    "@nestjs/core": ^10.4.7

    "@nestjs/schematics": ^10.2.3
    "@nestjs/cli": ^10.4.7

    "@types/express": ^5.0.0
    "@nestjs/platform-express": ^10.4.7

    "@nestjs/devtools-integration": ^0.1.6

    "@nestjs/swagger": ^8.0.5

    "@nestjs/terminus": ^10.2.3

    "@nestjs/throttler": ^6.2.1

    joi: ^17.13.3
    js-yaml: ^4.1.0
    "@types/js-yaml": ^4.0.9
    "@nestjs/config": ^3.3.0

    cache-manager: ^5.7.6
    "@nestjs/cache-manager": ^2.3.0

    supertest: ^7.0.0
    "@types/supertest": ^6.0.2
    "@nestjs/testing": ^10.4.7

    axios: ^1.7.7
    "@nestjs/axios": ^3.1.2

    helmet: ^8.0.0

    compression: ^1.7.5
    "@types/compression": ^1.7.5
