packages:
  - apps/*
  - packages/*
catalog:
    turbo: ^2.2.3
    "@turbo/gen": ^2.2.3
    "@turbo/workspaces": ^2.2.3

    "@biomejs/biome": ^1.9.4

    husky: ^9.1.6

    "@commitlint/cli": ^19.5.0
    "@commitlint/config-conventional": ^19.5.0
    "@commitlint/config-pnpm-scopes": ^19.5.0
    "@commitlint/prompt-cli": ^19.5.0
    "@commitlint/types": ^19.5.0

    node: ^23.1.0
    "@types/node": ^22.9.0

    typescript: ^5.6.3
    ts-loader: ^9.5.1
    ts-node: ^10.9.2
    tsconfig-paths: ^4.2.0
    tsup: ^8.3.5

    "jest": ^29.7.0
    jest-extended: ^4.0.2
    ts-jest: ^29.2.5
    "@types/jest": ^29.5.14
