# https://github.com/ejazahm3d/fullstack-turborepo-starter/blob/master/.github/workflows/api.yaml

name: api

on:
  push:
    branches: [master]
    paths:
      - "apps/api/**"
  pull_request:
    branches: [master]
    paths:
      - "apps/api/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DATABASE_URL: "mongodb://test:test@localhost:27017/test"
      HUSKY: 0

    strategy:
      matrix:
        node-version: [22.2.0]

    steps:
      - uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get pnpm store directory path
        id: pnpm-store-dir-path
        run: echo "::set-output name=dir::$(pnpm store path)"

      - name: Cache pnpm store
        uses: actions/cache@v4
        env:
            cache-name: cache-pnpm-store
        id: pnpm-store-cache
        with:
            path: ${{ steps.pnpm-store-dir-path.outputs.dir }}
            key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
                ${{ runner.os }}-pnpm-

      - run: pnpm install --frozen-lockfile
      - run: pnpm run prepare.ci.api
      - run: pnpm run build.ci.api
      - run: pnpm run test.ci.api